/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "cmsg_sub_service.pb-c.h"
void   cmsg_sub_entry_transport_info_init
                     (cmsg_sub_entry_transport_info         *message)
{
  static cmsg_sub_entry_transport_info init_value = CMSG_SUB_ENTRY_TRANSPORT_INFO_INIT;
  *message = init_value;
}
size_t cmsg_sub_entry_transport_info_get_packed_size
                     (const cmsg_sub_entry_transport_info *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_transport_info_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_sub_entry_transport_info_pack
                     (const cmsg_sub_entry_transport_info *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_transport_info_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_sub_entry_transport_info_pack_to_buffer
                     (const cmsg_sub_entry_transport_info *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_transport_info_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
cmsg_sub_entry_transport_info *
       cmsg_sub_entry_transport_info_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (cmsg_sub_entry_transport_info *)
     protobuf_c_message_unpack (&cmsg_sub_entry_transport_info_descriptor,
                                allocator, len, data);
}
void   cmsg_sub_entry_transport_info_free_unpacked
                     (cmsg_sub_entry_transport_info *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_transport_info_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cmsg_sub_entry_response_init
                     (cmsg_sub_entry_response         *message)
{
  static cmsg_sub_entry_response init_value = CMSG_SUB_ENTRY_RESPONSE_INIT;
  *message = init_value;
}
size_t cmsg_sub_entry_response_get_packed_size
                     (const cmsg_sub_entry_response *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_response_descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cmsg_sub_entry_response_pack
                     (const cmsg_sub_entry_response *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_response_descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cmsg_sub_entry_response_pack_to_buffer
                     (const cmsg_sub_entry_response *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_response_descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
cmsg_sub_entry_response *
       cmsg_sub_entry_response_unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (cmsg_sub_entry_response *)
     protobuf_c_message_unpack (&cmsg_sub_entry_response_descriptor,
                                allocator, len, data);
}
void   cmsg_sub_entry_response_free_unpacked
                     (cmsg_sub_entry_response *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &cmsg_sub_entry_response_descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor cmsg_sub_entry_transport_info_field_descriptors[11] =
{
  {
    "add",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, add),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "method_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, method_name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transport_type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, transport_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_sin_addr_s_addr",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_in_sin_addr_s_addr),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, in_sin_addr_s_addr),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "in_sin_port",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_in_sin_port),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, in_sin_port),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tipc_family",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_tipc_family),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, tipc_family),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tipc_addrtype",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_tipc_addrtype),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, tipc_addrtype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tipc_addr_name_name_type",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_tipc_addr_name_name_type),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, tipc_addr_name_name_type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tipc_addr_name_name_instance",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_tipc_addr_name_name_instance),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, tipc_addr_name_name_instance),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tipc_addr_name_domain",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_tipc_addr_name_domain),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, tipc_addr_name_domain),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tipc_scope",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, has_tipc_scope),
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_transport_info, tipc_scope),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_sub_entry_transport_info_field_indices_by_name[] = {
  0,   /* field[0] = add */
  3,   /* field[3] = in_sin_addr_s_addr */
  4,   /* field[4] = in_sin_port */
  1,   /* field[1] = method_name */
  9,   /* field[9] = tipc_addr_name_domain */
  8,   /* field[8] = tipc_addr_name_name_instance */
  7,   /* field[7] = tipc_addr_name_name_type */
  6,   /* field[6] = tipc_addrtype */
  5,   /* field[5] = tipc_family */
  10,   /* field[10] = tipc_scope */
  2,   /* field[2] = transport_type */
};
static const ProtobufCIntRange cmsg_sub_entry_transport_info_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor cmsg_sub_entry_transport_info_descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cmsg.sub_entry_transport_info",
  "subentrytransportinfo",
  "cmsg_sub_entry_transport_info",
  "cmsg",
  sizeof(cmsg_sub_entry_transport_info),
  11,
  cmsg_sub_entry_transport_info_field_descriptors,
  cmsg_sub_entry_transport_info_field_indices_by_name,
  1,  cmsg_sub_entry_transport_info_number_ranges,
  (ProtobufCMessageInit) cmsg_sub_entry_transport_info_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cmsg_sub_entry_response_field_descriptors[1] =
{
  {
    "return_value",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(cmsg_sub_entry_response, return_value),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cmsg_sub_entry_response_field_indices_by_name[] = {
  0,   /* field[0] = return_value */
};
static const ProtobufCIntRange cmsg_sub_entry_response_number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cmsg_sub_entry_response_descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "cmsg.sub_entry_response",
  "subentryresponse",
  "cmsg_sub_entry_response",
  "cmsg",
  sizeof(cmsg_sub_entry_response),
  1,
  cmsg_sub_entry_response_field_descriptors,
  cmsg_sub_entry_response_field_indices_by_name,
  1,  cmsg_sub_entry_response_number_ranges,
  (ProtobufCMessageInit) cmsg_sub_entry_response_init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor cmsg_sub_service_method_descriptors[1] =
{
  { "subscribe", &cmsg_sub_entry_transport_info_descriptor, &cmsg_sub_entry_response_descriptor },
};
const unsigned cmsg_sub_service_method_indices_by_name[] = {
  0         /* subscribe */
};
const ProtobufCServiceDescriptor cmsg_sub_service_descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "cmsg.sub_service",
  "subscribe",
  "cmsg_sub_service",
  "cmsg",
  1,
  cmsg_sub_service_method_descriptors,
  cmsg_sub_service_method_indices_by_name
};
int32_t cmsg_sub_service_subscribe(ProtobufCService *service,
                                   const cmsg_sub_entry_transport_info *input,
                                   cmsg_sub_entry_response_Closure closure,
                                   void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &cmsg_sub_service_descriptor);
  return service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void cmsg_sub_service_init (cmsg_sub_service_Service *service,
                             cmsg_sub_service_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &cmsg_sub_service_descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
