/*
 * Copyright 2017, Allied Telesis Labs New Zealand, Ltd
 *
 * Functional tests for the CMSG proxy library.
 */

#define _GNU_SOURCE
#include <np.h>
#include "cmsg_proxy_mem.c"
#include "cmsg_proxy.c"
#include "cmsg_proxy_functional_tests_proxy_def.h"
#include "cmsg_proxy_functional_tests_api_auto.h"
#include "cmsg_proxy_functional_tests_impl_auto.h"

/**
 * Mock the '_cmsg_proxy_library_handles_load' function to simply call
 * the autogenerated 'cmsg_proxy_array_get' and 'cmsg_proxy_array_size'
 * functions that are linked with the executable. Usually the CMSG proxy
 * will dynamically load every '_proxy_def' library that is on the device
 * however to simplify the functional tests we don't do this.
 */
void
sm_mock_cmsg_proxy_library_handles_load (void)
{
    _cmsg_proxy_service_info_init (cmsg_proxy_array_get (), cmsg_proxy_array_size ());
}

/**
 * Mock the 'cmsg_create_client_unix' used by the cmsg-proxy to instead be the
 * 'cmsg_create_client_loopback' function. This allows the proxy to execute the
 * CMSG IMPL functions locally which removes the need to run a separate thread/process
 * to implement the CMSG Unix socket server that the proxy usually expects. This makes
 * implementing functional tests much simpler.
 */
cmsg_client *
sm_mock_cmsg_create_client_unix (const ProtobufCServiceDescriptor *descriptor)
{
    return cmsg_create_client_loopback (CMSG_SERVICE (cmsg_proxy_functional_tests,
                                                      interface));
}

void
cmsg_proxy_functional_tests_interface_impl_test_get (const void *service)
{
    ant_result error_info = ANT_RESULT_INIT;
    ant_result_plus_bool send_msg = ANT_RESULT_PLUS_BOOL_INIT;

    CMSG_SET_FIELD_VALUE (&error_info, code, ANT_CODE_OK);
    CMSG_SET_FIELD_PTR (&send_msg, _error_info, &error_info);
    CMSG_SET_FIELD_VALUE (&send_msg, _data, true);

    cmsg_proxy_functional_tests_interface_server_test_getSend (service, &send_msg);
}

void
test_cmsg_proxy__functional (void)
{
    char *output_json = NULL;
    int http_status = 0;

    np_mock (_cmsg_proxy_library_handles_load, sm_mock_cmsg_proxy_library_handles_load);
    np_mock (cmsg_create_client_unix, sm_mock_cmsg_create_client_unix);

    cmsg_proxy_init ();

    cmsg_proxy ("/v1/test", NULL, CMSG_HTTP_GET, NULL, &output_json, &http_status);

    NP_ASSERT_STR_EQUAL (output_json, "true");
    NP_ASSERT_EQUAL (http_status, HTTP_CODE_OK);

    free (output_json);

    cmsg_proxy_deinit ();
}
