/*
 * Functional tests for server side validation.
 *
 * Copyright 2018, Allied Telesis Labs New Zealand, Ltd
 */

#include <np.h>
#include <stdint.h>
#include <cmsg_server.h>
#include "cmsg_functional_tests_api_auto.h"
#include "cmsg_functional_tests_impl_auto.h"
#include "cmsg_functional_tests_validation_auto.h"
#include "setup.h"

/**
 * This informs the compiler that the function is, in fact, being used even though it
 * doesn't look like it. This is useful for static functions that get found by NovaProva
 * using debug symbols.
 */
#define USED __attribute__ ((used))

static cmsg_client *test_client = NULL;
static cmsg_server *server = NULL;
static bool server_thread_run = true;
static bool server_ready = false;
static pthread_t server_thread;
static bool impl_func_called = false;


/**
 * Server processing function that should be run in a new thread.
 * Creates a server of given type and then begins polling the server
 * for any received messages. Once the main thread signals the polling
 * to stop the server is destroyed and the thread exits.
 */
static void *
server_thread_process (void *unused)
{
    server = cmsg_create_server_unix_rpc (CMSG_SERVICE (cmsg, test));

    int fd = cmsg_server_get_socket (server);
    int fd_max = fd + 1;

    fd_set readfds;
    FD_ZERO (&readfds);
    FD_SET (fd, &readfds);

    server_ready = true;

    while (server_thread_run)
    {
        cmsg_server_receive_poll (server, 1000, &readfds, &fd_max);
    }

    // Close accepted sockets before destroying server
    for (fd = 0; fd <= fd_max; fd++)
    {
        if (FD_ISSET (fd, &readfds))
        {
            close (fd);
        }
    }

    cmsg_destroy_server_and_transport (server);

    server = NULL;

    return 0;
}

/**
 * Create the server used to process the CMSG IMPL functions
 * in a new thread. Once the new thread is created the function
 * waits until the new thread signals that it is ready for processing.
 *
 * @param type - Transport type of the server to create
 */
static void
create_server_and_wait (void)
{
    int ret = 0;

    ret = pthread_create (&server_thread, NULL, &server_thread_process, NULL);

    NP_ASSERT_EQUAL (ret, 0);

    while (!server_ready)
    {
        usleep (100000);
    }
}

/**
 * Signal the server in the different thread to stop processing
 * and then wait for the server to be destroyed and the thread
 * to exit.
 */
static void
stop_server_and_wait (void)
{
    server_thread_run = false;
    pthread_join (server_thread, NULL);
}

/**
 * Common functionality to run before each test case.
 */
static int USED
set_up (void)
{
    server_ready = false;
    server_thread_run = true;

    /* Ignore SIGPIPE signal if it occurs */
    signal (SIGPIPE, SIG_IGN);

    cmsg_service_listener_mock_functions ();

    create_server_and_wait ();
    test_client = cmsg_create_client_unix (CMSG_DESCRIPTOR (cmsg, test));

    return 0;
}

/**
 * Common functionality to run at the end of each test case.
 */
static int USED
tear_down (void)
{
    stop_server_and_wait ();
    cmsg_destroy_client_and_transport (test_client);

    NP_ASSERT_NULL (server);

    return 0;
}

void
cmsg_test_impl_server_side_validation_test_integers (const void *service,
                                                     const
                                                     cmsg_message_with_integer_validation
                                                     *recv_msg)
{
    ant_result send_msg = ANT_RESULT_INIT;

    impl_func_called = true;

    CMSG_SET_FIELD_VALUE (&send_msg, code, ANT_CODE_OK);

    cmsg_test_server_server_side_validation_test_integersSend (service, &send_msg);
}

void
cmsg_test_impl_server_side_validation_test_strings (const void *service,
                                                    const
                                                    cmsg_message_with_string_validation
                                                    *recv_msg)
{
    ant_result send_msg = ANT_RESULT_INIT;

    cmsg_test_server_server_side_validation_test_stringsSend (service, &send_msg);
}

void
cmsg_test_impl_server_side_validation_test_sub_messages (const void *service,
                                                         const
                                                         cmsg_message_with_sub_message_validation
                                                         *recv_msg)
{
    ant_result send_msg = ANT_RESULT_INIT;

    cmsg_test_server_server_side_validation_test_sub_messagesSend (service, &send_msg);
}

/**
 * Test that the autogenerated validate function for a message functions
 * as expected when no error message is returned.
 */
void
test_integer_validate_function_no_error_message (void)
{
    cmsg_message_with_integer_validation send_msg =
        CMSG_MESSAGE_WITH_INTEGER_VALIDATION_INIT;

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 60);
    NP_ASSERT_FALSE (cmsg_message_with_integer_validation_validate (&send_msg, NULL, 0));

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 5);
    NP_ASSERT_FALSE (cmsg_message_with_integer_validation_validate (&send_msg, NULL, 0));

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 40);
    NP_ASSERT_TRUE (cmsg_message_with_integer_validation_validate (&send_msg, NULL, 0));
}

/**
 * Test that the autogenerated validate function for a message functions
 * as expected when an error message is returned.
 */
void
test_integer_validate_function_with_error_message (void)
{
    cmsg_message_with_integer_validation send_msg =
        CMSG_MESSAGE_WITH_INTEGER_VALIDATION_INIT;
    char err_str[512];

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 60);
    NP_ASSERT_FALSE (cmsg_message_with_integer_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'ge_ten_le_fifty' failed validation.");

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 5);
    NP_ASSERT_FALSE (cmsg_message_with_integer_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'ge_ten_le_fifty' failed validation.");

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 40);
    NP_ASSERT_TRUE (cmsg_message_with_integer_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));
}

/**
 * Test that the server side validation correctly catches and rejects
 * a message that doesn't validate.
 */
void
test_server_side_validation_failure (void)
{
    int ret = 0;
    cmsg_message_with_integer_validation send_msg =
        CMSG_MESSAGE_WITH_INTEGER_VALIDATION_INIT;
    ant_result *recv_msg = NULL;

    impl_func_called = false;

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 60);

    ret =
        cmsg_test_api_server_side_validation_test_integers (test_client, &send_msg,
                                                            &recv_msg);

    NP_ASSERT_EQUAL (ret, CMSG_RET_OK);
    NP_ASSERT_EQUAL (recv_msg->code, ANT_CODE_INVALID_ARGUMENT);
    NP_ASSERT_STR_EQUAL (recv_msg->message, "Field 'ge_ten_le_fifty' failed validation.");
    NP_ASSERT_FALSE (impl_func_called);

    CMSG_FREE_RECV_MSG (recv_msg);
}

/**
 * Test that the server side validation correctly continues to call
 * the impl function if the sent message validates.
 */
void
test_server_side_validation_success (void)
{
    int ret = 0;
    cmsg_message_with_integer_validation send_msg =
        CMSG_MESSAGE_WITH_INTEGER_VALIDATION_INIT;
    ant_result *recv_msg = NULL;

    impl_func_called = false;

    CMSG_SET_FIELD_VALUE (&send_msg, ge_ten_le_fifty, 40);

    ret =
        cmsg_test_api_server_side_validation_test_integers (test_client, &send_msg,
                                                            &recv_msg);

    NP_ASSERT_EQUAL (ret, CMSG_RET_OK);
    NP_ASSERT_EQUAL (recv_msg->code, ANT_CODE_OK);
    NP_ASSERT_NULL (recv_msg->message);
    NP_ASSERT_TRUE (impl_func_called);

    CMSG_FREE_RECV_MSG (recv_msg);
}

/**
 * Test that the autogenerated ip address validate functionality works as
 * expected for string fields.
 */
void
test_ip_address_format_validation (void)
{
    cmsg_message_with_string_validation send_msg = CMSG_MESSAGE_WITH_STRING_VALIDATION_INIT;
    char err_str[512];

    CMSG_SET_FIELD_PTR (&send_msg, ip_address, NULL);
    NP_ASSERT_TRUE (cmsg_message_with_string_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&send_msg, ip_address, "127.0.0.1");
    NP_ASSERT_TRUE (cmsg_message_with_string_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&send_msg, ip_address, "::1");
    NP_ASSERT_TRUE (cmsg_message_with_string_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&send_msg, ip_address, "blah");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'ip_address' must be in IP address format.");

    CMSG_SET_FIELD_PTR (&send_msg, ip_address, "127.00.0.1");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'ip_address' must be in IP address format.");

    CMSG_SET_FIELD_PTR (&send_msg, ip_address, "300.0.0.1");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'ip_address' must be in IP address format.");

    CMSG_SET_FIELD_PTR (&send_msg, ip_address, "192.168.1.10/27");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'ip_address' must be in IP address format.");
}

/**
 * Test that the auto generated UTC timestamp validate functionality works as
 * expected for string fields.
 */
void
test_utc_timestamp_format_validation (void)
{
    cmsg_message_with_string_validation send_msg = CMSG_MESSAGE_WITH_STRING_VALIDATION_INIT;
    char err_str[512];

    CMSG_SET_FIELD_PTR (&send_msg, timestamp, NULL);
    NP_ASSERT_TRUE (cmsg_message_with_string_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&send_msg, timestamp, "2019-02-02T11:11:11Z");
    NP_ASSERT_TRUE (cmsg_message_with_string_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&send_msg, timestamp, "2019/03/03T22:12:21");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'timestamp' must be in UTC timestamp format.");

    CMSG_SET_FIELD_PTR (&send_msg, timestamp, "2019-03-03T22:12:21");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'timestamp' must be in UTC timestamp format.");
}

/**
 * Test that the auto generated MAC address validate functionality works as
 * expected for string fields.
 */
void
test_mac_address_format_validation (void)
{
    cmsg_message_with_string_validation send_msg = CMSG_MESSAGE_WITH_STRING_VALIDATION_INIT;
    char err_str[512];

    CMSG_SET_FIELD_PTR (&send_msg, mac_address, NULL);
    NP_ASSERT_TRUE (cmsg_message_with_string_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&send_msg, mac_address, "1234.AAbb.33ff");
    NP_ASSERT_TRUE (cmsg_message_with_string_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&send_msg, mac_address, "123.AAbb.33ff");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'mac_address' must be in MAC address format.");

    CMSG_SET_FIELD_PTR (&send_msg, mac_address, "zzzz.zzzz.zzzz");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'mac_address' must be in MAC address format.");

    CMSG_SET_FIELD_PTR (&send_msg, mac_address, "blah");
    NP_ASSERT_FALSE (cmsg_message_with_string_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'mac_address' must be in MAC address format.");
}

/**
 * Test that the auto generated sub message field validate functionality works as
 * expected.
 */
void
test_sub_message_field_validation (void)
{
    cmsg_message_with_sub_message_validation send_msg =
        CMSG_MESSAGE_WITH_SUB_MESSAGE_VALIDATION_INIT;
    cmsg_message_with_string_validation sub_msg = CMSG_MESSAGE_WITH_STRING_VALIDATION_INIT;
    char err_str[512];

    CMSG_SET_FIELD_PTR (&sub_msg, mac_address, NULL);
    CMSG_SET_FIELD_PTR (&send_msg, sub, &sub_msg);
    NP_ASSERT_TRUE (cmsg_message_with_sub_message_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&sub_msg, mac_address, "1234.AAbb.33ff");
    CMSG_SET_FIELD_PTR (&sub_msg, timestamp, "2019-02-02T11:11:11Z");
    CMSG_SET_FIELD_PTR (&sub_msg, ip_address, "127.0.0.1");

    CMSG_SET_FIELD_PTR (&send_msg, sub, &sub_msg);

    NP_ASSERT_TRUE (cmsg_message_with_sub_message_validation_validate
                    (&send_msg, err_str, sizeof (err_str)));

    CMSG_SET_FIELD_PTR (&sub_msg, mac_address, "zzzz.zzzz.zzzz");
    CMSG_SET_FIELD_PTR (&send_msg, sub, &sub_msg);

    NP_ASSERT_FALSE (cmsg_message_with_sub_message_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'mac_address' must be in MAC address format.");

    CMSG_SET_FIELD_PTR (&sub_msg, timestamp, "2019/03/03T22:12:21");
    CMSG_SET_FIELD_PTR (&send_msg, sub, &sub_msg);

    NP_ASSERT_FALSE (cmsg_message_with_sub_message_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'timestamp' must be in UTC timestamp format.");

    CMSG_SET_FIELD_PTR (&sub_msg, ip_address, "300.0.0.1");
    CMSG_SET_FIELD_PTR (&send_msg, sub, &sub_msg);

    NP_ASSERT_FALSE (cmsg_message_with_sub_message_validation_validate
                     (&send_msg, err_str, sizeof (err_str)));
    NP_ASSERT_STR_EQUAL (err_str, "Field 'ip_address' must be in IP address format.");
}
