/*
 * Copyright 2016, Allied Telesis Labs New Zealand, Ltd
 */

#include <np.h>
#include "cmsg_proxy.c"
#include "cmsg_proxy_unit_tests_proxy_def.h"
#include "cmsg_proxy_unit_tests_api_auto.h"

/**
 * Novaprova setup function
 */
static int
setup (void)
{
    /* Create GNode cmsg proxy entry tree */
    proxy_entries_tree = g_node_new ("CMSG_API");

    return 0;
}

/**
 * Function Tested: _cmsg_proxy_list_init()
 *
 * Tests that the proxy list is the correct length after _cmsg_proxy_list_init()
 * is called.
 */
void
test_cmsg_proxy_list_init__list_length (void)
{
    _cmsg_proxy_list_init (cmsg_proxy_unit_tests_proxy_array_get (),
                           cmsg_proxy_unit_tests_proxy_array_size ());
    NP_ASSERT_EQUAL (g_list_length (proxy_entries_list),
                     cmsg_proxy_unit_tests_proxy_array_size ());

    _cmsg_proxy_list_init (cmsg_proxy_unit_tests_proxy_array_get (),
                           cmsg_proxy_unit_tests_proxy_array_size ());
    NP_ASSERT_EQUAL (g_list_length (proxy_entries_list),
                     cmsg_proxy_unit_tests_proxy_array_size () * 2);

    _cmsg_proxy_list_init (cmsg_proxy_unit_tests_proxy_array_get (),
                           cmsg_proxy_unit_tests_proxy_array_size ());
    NP_ASSERT_EQUAL (g_list_length (proxy_entries_list),
                     cmsg_proxy_unit_tests_proxy_array_size () * 3);
}

/**
 * Function Tested: _cmsg_proxy_list_init()
 *
 * Tests that the first proxy list entry points at the expected autogenerated data.
 */
void
test_cmsg_proxy_list_init__list_entries (void)
{
    _cmsg_proxy_list_init (cmsg_proxy_unit_tests_proxy_array_get (),
                           cmsg_proxy_unit_tests_proxy_array_size ());
    cmsg_service_info *entry =
        (cmsg_service_info *) (g_list_first (proxy_entries_list))->data;

    NP_ASSERT_PTR_EQUAL (entry, cmsg_proxy_unit_tests_proxy_array_get ());
    NP_ASSERT_PTR_EQUAL (entry->service_descriptor,
                         &cmsg_proxy_unit_tests_interface_descriptor);
    NP_ASSERT_EQUAL (entry->http_verb, CMSG_HTTP_PUT);
}

/**
 * Function Tested: _cmsg_proxy_find_service_from_url_and_verb()
 *
 * Tests that the function finds the correct service entry when passed
 * a known URL and verb or returns NULL for an unknown URL and verb.
 */
void
test_cmsg_proxy_find_service_from_url_and_verb (void)
{
    const cmsg_service_info *entry;

    _cmsg_proxy_list_init (cmsg_proxy_unit_tests_proxy_array_get (),
                           cmsg_proxy_unit_tests_proxy_array_size ());

    entry = _cmsg_proxy_find_service_from_url_and_verb ("/v1/test", CMSG_HTTP_PUT);
    NP_ASSERT_PTR_NOT_EQUAL (entry, NULL);
    NP_ASSERT_EQUAL (entry->http_verb, CMSG_HTTP_PUT);

    entry = _cmsg_proxy_find_service_from_url_and_verb ("BAD URL", CMSG_HTTP_PUT);
    NP_ASSERT_PTR_EQUAL (entry, NULL);

    entry = _cmsg_proxy_find_service_from_url_and_verb ("/v1/test", CMSG_HTTP_GET);
    NP_ASSERT_PTR_NOT_EQUAL (entry, NULL);
    NP_ASSERT_EQUAL (entry->http_verb, CMSG_HTTP_GET);

    entry = _cmsg_proxy_find_service_from_url_and_verb ("/v1/test", CMSG_HTTP_PATCH);
    NP_ASSERT_PTR_EQUAL (entry, NULL);
}

/**
 * Function Tested: _cmsg_proxy_convert_json_to_protobuf()
 *
 * Tests that valid input is correctly converted into a protobuf message
 */
void
test_cmsg_proxy_convert_json_to_protobuf__valid_input (void)
{
    ProtobufCMessage *output = NULL;
    bool ret;
    char *json_str = "{\n    \"value\":true\n}";

    ret = _cmsg_proxy_convert_json_to_protobuf (json_str,
                                                &cmsg_proxy_unit_tests_cmsg_bool_descriptor,
                                                &output);

    free (output);
    NP_ASSERT_TRUE (ret);
}

/**
 * Function Tested: _cmsg_proxy_convert_json_to_protobuf()
 *
 * Tests that invalid input fails to be converted into a protobuf message
 */
void
test_cmsg_proxy_convert_json_to_protobuf__invalid_input (void)
{
    ProtobufCMessage *output = NULL;
    bool ret;
    char *json_str;

    /* value is not quoted correctly */
    json_str = "{\n    value\":true\n}";

    ret = _cmsg_proxy_convert_json_to_protobuf (json_str,
                                                &cmsg_proxy_unit_tests_cmsg_bool_descriptor,
                                                &output);

    NP_ASSERT_FALSE (ret);

    /* json string is missing closing bracket */
    json_str = "{\n    \"value\":true\n";

    ret = _cmsg_proxy_convert_json_to_protobuf (json_str,
                                                &cmsg_proxy_unit_tests_cmsg_bool_descriptor,
                                                &output);

    NP_ASSERT_FALSE (ret);
}

/**
 * Function Tested: _cmsg_proxy_server_name_get()
 *
 * Tests that the correct server name is returned from the
 * CMSG service descriptor
 */
void
test_cmsg_proxy_server_name_get (void)
{
    char *svr_name = NULL;

    svr_name = _cmsg_proxy_server_name_get (&cmsg_proxy_unit_tests_interface_descriptor);

    NP_ASSERT_STR_EQUAL (svr_name, "cmsg_proxy_unit_tests-interface");
    free (svr_name);
}

struct servent mock_servent_data;

struct servent *
sm_mock_getservbyname (char *unused1, char *unused2)
{
    mock_servent_data.s_port = 10000;

    return &mock_servent_data;
}

/**
 * Function Tested: _cmsg_proxy_create_client()
 *
 * Tests that the function correctly creates a CMSG client
 * from a valid descriptor
 */
void
test_cmsg_proxy_create_client (void)
{
    np_mock (getservbyname, sm_mock_getservbyname);

    _cmsg_proxy_create_client (&cmsg_proxy_unit_tests_interface_descriptor);

    NP_ASSERT_EQUAL (g_list_length (proxy_clients_list), 1);
}

struct cmsg_client *
sm_mock_cmsg_client_new__returns_null (cmsg_transport *transport,
                                       const ProtobufCServiceDescriptor *descriptor)
{
    return NULL;
}

/**
 * Function Tested: _cmsg_proxy_create_client()
 *
 * Tests that no memory is leaked if the internal cmsg_client_new()
 * function fails
 */
void
test_cmsg_proxy_create_client__memory_leaks (void)
{
    np_mock (getservbyname, sm_mock_getservbyname);
    np_mock (cmsg_client_new, sm_mock_cmsg_client_new__returns_null);

    _cmsg_proxy_create_client (&cmsg_proxy_unit_tests_interface_descriptor);
    _cmsg_proxy_create_client (&cmsg_proxy_unit_tests_interface_descriptor);

    NP_ASSERT_EQUAL (g_list_length (proxy_clients_list), 0);
}

/**
 * Function Tested: _cmsg_proxy_clients_init()
 *
 * Tests that the function correctly creates the required CMSG clients
 */
void
test_cmsg_proxy_clients_init (void)
{
    np_mock (getservbyname, sm_mock_getservbyname);

    _cmsg_proxy_list_init (cmsg_proxy_unit_tests_proxy_array_get (),
                           cmsg_proxy_unit_tests_proxy_array_size ());

    _cmsg_proxy_clients_init ();
    NP_ASSERT_EQUAL (g_list_length (proxy_clients_list), 1);

    _cmsg_proxy_clients_init ();
    NP_ASSERT_EQUAL (g_list_length (proxy_clients_list), 1);
}

/**
 * Function Tested: _cmsg_proxy_convert_protobuf_to_json()
 *
 * Tests that valid input is correctly converted into a json string
 */
void
test_cmsg_proxy_convert_protobuf_to_json (void)
{
    cmsg_proxy_unit_tests_cmsg_bool proto_msg = CMSG_PROXY_UNIT_TESTS_CMSG_BOOL_INIT;
    char *json_str = NULL;
    bool ret = false;

    CMSG_SET_FIELD_VALUE (&proto_msg, value, true);

    ret = _cmsg_proxy_convert_protobuf_to_json ((ProtobufCMessage *) &proto_msg, &json_str);

    NP_ASSERT_TRUE (ret);
    NP_ASSERT_STR_EQUAL (json_str, "{\n    \"value\": true\n}");

    free (json_str);
}

/**
 * Function Tested: _cmsg_proxy_add_service_info()
 *
 * Tests that input URL string is correctly tokenized into the tree
 */
void
test_cmsg_proxy_add_service_info (void)
{
    _cmsg_proxy_add_service_info ("/v1/statistics/interfaces/enabled");
    NP_ASSERT_EQUAL (g_node_n_nodes (proxy_entries_tree, G_TRAVERSE_ALL), 5);

    _cmsg_proxy_add_service_info ("/v1/statistics/interfaces/disabled");
    NP_ASSERT_EQUAL (g_node_n_nodes (proxy_entries_tree, G_TRAVERSE_ALL), 6);

    _cmsg_proxy_add_service_info ("/v1/statistics/disabled");
    NP_ASSERT_EQUAL (g_node_n_nodes (proxy_entries_tree, G_TRAVERSE_ALL), 7);

    _cmsg_proxy_add_service_info ("/v2/statistics/interfaces/disabled");
    NP_ASSERT_EQUAL (g_node_n_nodes (proxy_entries_tree, G_TRAVERSE_ALL), 11);

    /* Add the same URL again. */
    _cmsg_proxy_add_service_info ("/v2/statistics/interfaces/disabled");
    NP_ASSERT_EQUAL (g_node_n_nodes (proxy_entries_tree, G_TRAVERSE_ALL), 11);
}
